# OVERRIDE: Local Development
services:
  api:
    image: coverit-docgen-dev-local
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src

  worker:
    image: coverit-docgen-dev-local
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
      - ./worker.py:/app/worker.py