FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends gcc && \
    rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir uv

COPY pyproject.toml uv.lock ./

RUN uv sync

ENV PATH="/app/.venv/bin:$PATH"

RUN playwright install --with-deps chromium

ENV ENVIRONMENT=development
ENV PYTHONUNBUFFERED=1

CMD ["watchfiles", "arq worker.WorkerSettings", "src", "worker.py"]